### ISSUE TITLE
HBS Highlighting not working

### ISSUE THREAD

**Issue by alexlafroscia** [dustinfarris/vim-htmlbars-inline-syntax#2]
I can't seem to get this to work. Not seeing any errors in `:messages`, startup seems fine too. Does it I have `vim-mustache-handlebars` installed; does this depend on a particular JS highlighting plugin? 

<img width="430" alt="screen shot 2016-12-07 at 11 42 51 am" src="https://cloud.githubusercontent.com/assets/1645881/20983702/511a4ad8-bc72-11e6-86b2-46fcaca653b8.png">

**Comment by dustinfarris** [comment]
Yes, I'm using [pangloss/vim-javascript](https://github.com/pangloss/vim-javascript) which the plugin relies on for the block inside a JS object.

Which plugin are you using for JS syntax?  Maybe I can make it work with both.

**Comment by alexlafroscia** [comment]
I use the same one...

I had a JSX plugin enabled, but removed that, thinking it might be part of the issue. Apparently it's not, though.

**Comment by alexlafroscia** [comment]
Hmm, so if I manually run `:call htmlbars_inline_syntax#highlight()` in the JS file, it starts working. Must be something wrong with the `autocmd`

**Comment by alexlafroscia** [comment]
Changing the `autocmd` to 

```vim
autocmd BufRead,BufNewFile *.js HighlightInlineHbs
```

Seemed to work. Maybe it's a race condition with then the command gets fired?

**Comment by alexlafroscia** [comment]
This looks great! Although it does remove the highlighting from the `hbs` and the back-ticks. Unintended side-effect?

<img width="416" alt="screen shot 2016-12-07 at 12 48 36 pm" src="https://cloud.githubusercontent.com/assets/1645881/20985973/91480e5c-bc7b-11e6-8e6d-fc6510860224.png">

**Comment by dustinfarris** [comment]
Thanks for digging on this!  I will update the `autocmd` in the README.

Yes, it seems that the tag (hbs) and the back-ticks lose their syntax group somehow.  Definitely not intended.
